---
- hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yaml
  tasks:
    - name: Add Harbor chart repo
      kubernetes.core.helm_repository:
        kubeconfig: ~/.kube/config
        name: stable
        repo_url: "https://helm.goharbor.io"

    - name: Install Harbor
      kubernetes.core.helm:
        kubeconfig: ~/.kube/config
        name: harbor
        chart_ref: stable/harbor
        release_namespace: harbor
        create_namespace: true
        set_values:
        - value: expose.ingress.hosts.core={{ harbor_domain_name }}
        - value: expose.ingress.hosts.notary={{ harbor_notary_domain_name }}
        - value: expose.tls.enabled=false
        - value: externalURL=http://{{ harbor_domain_name }}
        - value: expose.ingress.annotations/ssl-redirect=false

    # Install Helm push plugin in order to push helm charts to registry
    - name: Helm Plugin
      shell: | 
        helm plugin install https://github.com/chartmuseum/helm-push
      ignore_errors: true
    
    - name: Helm Push Harbor
      shell: | 
        helm package ./harbor_chart --destination ./harbor_chart --version 0.1
        helm registry login -u admin -p Harbor12345 http://{{ harbor_domain_name }} --insecure
        helm push ./harbor_chart/harbor-0.1.tgz oci://{{ harbor_domain_name }} --kube-insecure-skip-tls-verify
      ignore_errors: true

    - name: Add Keycloak chart repo
      kubernetes.core.helm_repository:
        kubeconfig: ~/.kube/config
        name: keycloak
        repo_url: "https://charts.bitnami.com/bitnami"
      ignore_errors: true

    - name: Install Keycloak
      kubernetes.core.helm:
        kubeconfig: ~/.kube/config
        name: keycloak-rel
        chart_ref: keycloak/keycloak
        release_namespace: keycloak
        create_namespace: true

    